[tool.ruff]
line-length = 120
indent-width = 4

[tool.mypy]
allow_untyped_calls = true
check_untyped_defs = true
disable_error_code = "import-untyped"
exclude = [
    "ecoflow_cloud/config_flow.py",
]